version: "3"
services:
    zookeeper:
        image: zookeeper:3.4.9
        ports: 
            - "2181:2181"  
    kafka:
        image: confluentinc/cp-kafka:5.3.0
        depends_on:
          - zookeeper  
        ports:
            - "9092:9092"
        environment: 
            KAFKA_BROKER_ID: -1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    mongo:
        image: mongo
        restart: always
        command: --serviceExecutor adaptive
        ports: 
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express
        restart: always
        links: 
            - mongo
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
    exam-orders:
        image: exam-orders
        ports: 
            - "3000:3000"    
        depends_on: 
            - kafka
            - mongo
    exam-dishes:
        image: exam-dishes
        ports: 
            - "4000:3000"
        depends_on: 
            - kafka
            - mongo
    exam-client:
        image: exam-client
        ports: 
            - "5000:3000"
        depends_on: 
            -kafka
            -mongo
    exam-api-gateway:
        image: exam-api-gateway
        ports: 
            - "8080:8080"


        