http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  orders:
    host: localhost
    paths: 
      - '/Orders'
      - '/Order/add'
  dishes:
    host: localhost
    paths:
      - '/Dishes'
      - '/Dish/add'
serviceEndpoints:
  orders:
    url: 'http://localhost:3000'
  dishes:
    url: 'http://localhost:4000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
